brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
namesrvAddr = rocketmq-namesrv:9876
brokerIP1 = rocketmq-broker
listenPort = 10911
storePathRootDir = /home/rocketmq/store
storePathCommitLog = /home/rocketmq/store/commitlog
timerWheelEnable = true
autoCreateTopicEnable = true
