spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: 192.168.199.128
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 100
        max-idle: 20
        min-idle: 2
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  #程序启动的时候就和数据库建立连接
  mvc:
    servlet:
      load-on-startup: 1


mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.hmdp: debug


